In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import scipy.stats as stats
import bokeh as bk
%matplotlib inline

In [93]:
X = stats.binom(n=30, p=0.7)

In [94]:
X.expect()

20.999999999999847

In [95]:
X.var()

6.3000000000000007

Найдём вероятность $P(X=7)$:

In [97]:
X.pmf(7)

1.5783752006340861e-07

In [96]:
values = X.rvs(20)

In [24]:
values

array([ 8, 10,  5,  8,  7,  5,  6,  7,  7,  7,  6,  7,  6,  8,  7,  7,  7,
        5,  8,  9])

In [52]:
4 - 3 == 1

True

In [54]:
0.4 - 0.3 == 0.1

False

In [55]:
0.1 + 0.3 == 0.4

True

In [56]:
X.pmf(0)

0.0012379400392853797

In [57]:
X.cdf(10)

0.97438374466467348

In [58]:
v = np.arange(2, 8)

In [59]:
v

array([2, 3, 4, 5, 6, 7])

In [60]:
v = np.arange(2, 8, 0.3)

In [61]:
v

array([ 2. ,  2.3,  2.6,  2.9,  3.2,  3.5,  3.8,  4.1,  4.4,  4.7,  5. ,
        5.3,  5.6,  5.9,  6.2,  6.5,  6.8,  7.1,  7.4,  7.7])

In [64]:
np.arange(start=2, stop=8, step=0.3)

array([ 2. ,  2.3,  2.6,  2.9,  3.2,  3.5,  3.8,  4.1,  4.4,  4.7,  5. ,
        5.3,  5.6,  5.9,  6.2,  6.5,  6.8,  7.1,  7.4,  7.7])

In [65]:
v = np.arange(2, 8)

In [68]:
X.pmf(v)

array([ 0.03365649,  0.07853182,  0.13252245,  0.17227918,  0.17945748,
        0.1538207 ])

In [69]:
np.sum(X.pmf(v))

0.75026812836502677

In [82]:
values = X.rvs(1000)

In [83]:
values

array([ 3,  8,  6,  7, 11,  6,  6,  3,  5,  6,  7,  8,  5,  3,  5,  9,  4,
        6,  9,  2,  6, 10,  4,  6,  9,  4,  6,  7,  7,  6,  4,  6,  5,  6,
        5,  8,  8,  5,  6,  5,  6,  5,  7,  5,  6,  7,  5,  9,  4,  7,  5,
        5,  7,  6,  5,  1,  3,  7,  6,  7, 10,  7,  3,  5,  6,  4, 10, 10,
        8,  6,  8,  4,  5,  6,  7,  6,  4,  5,  5,  5,  4,  5,  6,  8,  8,
        6,  6,  8,  9,  7,  8, 10,  2,  9,  5,  6,  8,  7,  4,  7,  3,  5,
        8,  6,  6,  7,  8,  7,  1,  5,  6,  3,  6,  7,  8, 10,  4,  4,  7,
        4,  4,  6,  4,  8,  8,  2,  6,  8, 11,  5,  4,  9,  9,  4,  6,  7,
        8,  4,  7,  8,  6,  4,  2,  5,  8,  3,  1,  5,  3,  4,  2,  6,  7,
        5,  4,  5,  6, 10, 12,  4,  2,  8,  9,  6,  8,  8,  7,  9,  2,  5,
        5,  3,  9,  2,  7,  3,  5,  5,  4,  6,  6,  5,  7,  4,  4,  5,  5,
        4,  9,  8,  3,  5,  4,  6,  5,  6,  9,  5,  7,  6,  7,  3,  7, 10,
        6,  5,  7,  7,  7,  4, 10, 10,  5,  6,  2, 11,  8,  7,  8,  4,  5,
        4,  6,  3,  9,  6

In [72]:
values ** 3

array([  27, 1000,  729, 1000,   64,   64,   64,  729,   64,  125,  512,
         27, 1728,  343,  343,  512,  125,  512,  343,  125,   64,  512,
        343,  125,  512,  343,  216,  125,  512,  512,   64,  216,  125,
         27,    8, 1000,  125,   64,  125,  216,  125,  216,  512,  343,
        512,   64,   64,   27, 1331,  125,  343,  125,  729,  216,   64,
        216,   27,  216,    8,  343,  343,  343,  216,  216,  216,  125,
        216,  343,   27,    8,  343, 1000,   64,  216,  343,  125,  216,
        343,  125,   64,  125,  216,    8,  512,  512,  216,  729,  343,
        125,   64,  125,  125,  216,  216,   64,  125,  343,  729,  216,
       1000, 1331,   64,  125,  512,  729,  216,  216,   64,   64,  343,
        125,   64,  216,  125,    8,  216, 1331,  216,  729,  216,   64,
        343,   27,  125,   27,  512,  216,    8,   27, 1000,  125, 1331,
        343,   64,  216,  216,  512,  125, 1000,  216,   27,   64,   27,
        125, 1000,  343,   27,   27,  216,   64,  7

In [73]:
np.mean(values ** 3)

299.351

In [74]:
np.mean(values)

5.9569999999999999

In [81]:
np.random.seed(7)

In [86]:
82 // 13

6

In [87]:
82 % 13

4

In [88]:
49 % 13

10

In [89]:
v = X.rvs(50)

In [90]:
w = X.rvs(50)

In [92]:
np.sum(v > w)

15