Призываем верных демонов и произносим магическое заклинание для быстрого построения графиков:

In [3]:
import numpy as np
import pandas as pd
import seaborn as sns
import scipy.stats as stats
import bokeh as bk
%matplotlib inline

Создадим случайную величину X имеющую биномиальное распределение:

In [4]:
X = stats.binom(n=30, p=0.7)

Математическое ожидание:

In [5]:
X.expect()

20.999999999999847

Дисперсия:

In [6]:
X.var()

6.3000000000000007

Найдём вероятность $P(X=7)$:

In [7]:
X.pmf(7)

1.5783752006340861e-07

Найдём вероятность $P(X=0)$:

In [8]:
X.pmf(0)

2.0589113209464959e-16

Почему у нас вышли не идеально точные результаты? Давайте разберёмся!

In [9]:
4 - 3 == 1

True

In [10]:
0.4 - 0.3 == 0.1

False

Проблема в том, что десятичные числа при преобразовании в двоичную систему могут стать периодическими с бесконечной записью!

In [11]:
0.1 + 0.3 == 0.4

True

Сгенерируем случайный вектор из 20 независимых значений нашего биномиального распределения:

In [12]:
values = X.rvs(20)

In [13]:
values

array([23, 24, 14, 21, 17, 25, 17, 21, 21, 22, 24, 20, 18, 21, 21, 19, 21,
       22, 22, 21])

Найдём вероятность $F(10)=P(X \leq 10)$:

In [14]:
X.cdf(10)

3.6870080768784921e-05

Последовательность чисел от 2 до 8:

In [15]:
v = np.arange(2, 8)

In [16]:
v

array([2, 3, 4, 5, 6, 7])

Арифметическая прогрессия:

In [17]:
np.arange(start=2, stop=8, step=0.3)

array([ 2. ,  2.3,  2.6,  2.9,  3.2,  3.5,  3.8,  4.1,  4.4,  4.7,  5. ,
        5.3,  5.6,  5.9,  6.2,  6.5,  6.8,  7.1,  7.4,  7.7])

Снова вернёмся к нашему вектору от 2 до 8:

In [18]:
v = np.arange(2, 8)

In [19]:
X.pmf(v)

array([  4.87618831e-13,   1.06192545e-11,   1.67253259e-10,
         2.02933954e-09,   1.97296900e-08,   1.57837520e-07])

А это $P(X \in [2; 8))$:

In [20]:
np.sum(X.pmf(v))

1.797749097474779e-07

На этот раз сгенерируем 1000 независимых значений случайной величины:

In [21]:
values = X.rvs(1000)

In [22]:
values

array([22, 22, 23, 18, 23, 19, 23, 25, 23, 18, 20, 19, 23, 25, 24, 21, 18,
       23, 22, 22, 19, 23, 21, 22, 16, 19, 23, 18, 21, 20, 16, 23, 22, 21,
       27, 22, 14, 18, 19, 21, 20, 23, 22, 25, 20, 18, 17, 25, 14, 23, 19,
       19, 28, 17, 23, 20, 22, 22, 23, 21, 25, 19, 24, 20, 23, 21, 20, 17,
       22, 20, 23, 18, 21, 20, 19, 26, 21, 23, 20, 24, 26, 23, 20, 19, 24,
       21, 23, 21, 19, 23, 18, 21, 20, 17, 21, 19, 21, 20, 16, 21, 20, 21,
       20, 22, 19, 22, 24, 18, 24, 22, 22, 22, 19, 24, 23, 21, 24, 24, 22,
       24, 21, 23, 19, 22, 24, 21, 20, 21, 25, 22, 19, 16, 15, 21, 21, 16,
       18, 20, 26, 21, 22, 23, 20, 25, 12, 21, 24, 25, 20, 19, 21, 16, 19,
       16, 25, 22, 20, 25, 23, 19, 22, 24, 20, 21, 24, 17, 17, 21, 18, 17,
       20, 21, 22, 24, 23, 25, 22, 23, 21, 26, 20, 17, 21, 22, 19, 23, 19,
       24, 16, 21, 22, 21, 21, 15, 25, 25, 23, 22, 25, 23, 22, 21, 19, 22,
       24, 20, 23, 23, 20, 23, 18, 24, 19, 25, 20, 19, 24, 20, 21, 25, 20,
       25, 22, 25, 16, 20

Возводим в куб:

In [23]:
values ** 3

array([10648, 10648, 12167,  5832, 12167,  6859, 12167, 15625, 12167,
        5832,  8000,  6859, 12167, 15625, 13824,  9261,  5832, 12167,
       10648, 10648,  6859, 12167,  9261, 10648,  4096,  6859, 12167,
        5832,  9261,  8000,  4096, 12167, 10648,  9261, 19683, 10648,
        2744,  5832,  6859,  9261,  8000, 12167, 10648, 15625,  8000,
        5832,  4913, 15625,  2744, 12167,  6859,  6859, 21952,  4913,
       12167,  8000, 10648, 10648, 12167,  9261, 15625,  6859, 13824,
        8000, 12167,  9261,  8000,  4913, 10648,  8000, 12167,  5832,
        9261,  8000,  6859, 17576,  9261, 12167,  8000, 13824, 17576,
       12167,  8000,  6859, 13824,  9261, 12167,  9261,  6859, 12167,
        5832,  9261,  8000,  4913,  9261,  6859,  9261,  8000,  4096,
        9261,  8000,  9261,  8000, 10648,  6859, 10648, 13824,  5832,
       13824, 10648, 10648, 10648,  6859, 13824, 12167,  9261, 13824,
       13824, 10648, 13824,  9261, 12167,  6859, 10648, 13824,  9261,
        8000,  9261,

Среднее арифметическое или оценка для $E(X^3)$:

In [24]:
np.mean(values ** 3)

9673.357

Оценка для математического ожидания:

In [25]:
np.mean(values)

21.013000000000002

Деление нацело:

In [26]:
82 // 13

6

Остаток от деления:

In [27]:
82 % 13

4

In [28]:
49 % 13

10

Установим зерно генератора случайных чисел:

In [43]:
np.random.seed(7)

In [44]:
v = X.rvs(50)

In [45]:
np.sum(v > 20)

32