# Семинар 72. Очень краткое введение в питон :)

дата: 2016-09-26

конспектировал: Винни-Пух

## О незаменимости вероятностей

Пара формул:

Решаем уравнение $x + 7 = 8$

$$
\frac{45}{56}=7 \sqrt{7} + C_{n}^{k+2}  
$$

## О пользе математического ожидания

Ссылка на [книжку Воронцова по латеху](www.ccas.ru/voron/download/voron05latex.pdf).

Для красоты --- портрет Гаусса:
![](http://cdn2.rare-earth-magnets.com/images/content/johann_carl_friedrich_gauss.jpg)




Простые вычисления в базовом питоне:

In [1]:
5 + 9

14

In [4]:
import scipy.misc

In [5]:
scipy.misc.factorial(7)

array(5040.0)

In [7]:
from scipy.misc import *

In [8]:
factorial(9)

array(362880.0)

In [11]:
comb(30, 4)

27405.0

In [12]:
from numpy import *

In [13]:
arange(4, 10)

array([4, 5, 6, 7, 8, 9])

In [15]:
a = [4, 5, 6]

In [16]:
sum(a)

15

In [17]:
a

[4, 5, 6]

In [18]:
a = array([4, 5, 6])

In [19]:
a

array([4, 5, 6])

In [20]:
sum(a)

15

In [21]:
prod(a)

120

In [22]:
cos(a)

array([-0.65364362,  0.28366219,  0.96017029])